services:
  auth_api:
    container_name: "auth_api"
    build:
      context: .
      dockerfile: authUser/Dockerfile
    ports:
      - "8080:8080"
  post_api:
    container_name: "post_api"
    build:
      context: .
      dockerfile: postService/Dockerfile
    ports:
      - "8081:8081"