spring.application.name=postService

spring.thymeleaf.check-template-location=false
logging.level.org.springframework=DEBUG
logging.level.org.example.postservice=DEBUG

cloud.aws.s3.bucket-name=cloudy-way
cloud.aws.credentials.access-key = ${S3_ACCESS_KEY}
cloud.aws.credentials.secret-key = ${S3_SECRET_KEY}