spring.application.name=Here_API_Service
server.port=5000

here_api_key=${HERE_API_KEY}
discover_base_url=https://discover.search.hereapi.com/v1/discover
geocode_base_url=https://geocode.search.hereapi.com/v1/geocode
rabbitmq_url=${RABBITMQ_URL}
bbox=22.14,44.38,40.23,52.38